name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      env:
        PYV: ${{ matrix.python-version }}
      run: |
        pip install -r requirements.txt
        pip install "flake8<4" "importlib-metadata<5"
        pip install youtube-dl
        if [[ "$PYV" != "3.4" && "$PYV" != "3.5" ]]; then pip install yt-dlp; fi

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        make test

    - name: Test autogeneration of man pages, bash/zsh/fish completion, etc
      run: |
        make
